import type { Metadata } from "next";
import "./globals.css";
import { poppins, inter, lato } from "./fonts";
import { cn } from "@/lib/utils";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { TrackingCapture } from "@/components/tracking-capture";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "overflow-x-hidden", poppins.variable, inter.variable, lato.variable)}
    >
      <body className="min-h-full flex flex-col">
        <TrackingCapture />
        <div
          className="fixed inset-0 -z-20 bg-cover bg-center"
          style={{ backgroundImage: "url('/wallpaper.jpg')" }}
        />
        <div className="fixed inset-0 -z-10 bg-hero-gradient" />

        <Header />

        <main className="flex-1">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
